### ISSUE TITLE
Question / Enhancement - rotation support in Figma prototype 

### ISSUE THREAD

**Issue by Design2Well** [chuanqisun/figma-plugin-spacemouse#2]
Hi Chuanqisun, 

I just installed this plugin without a SpaceMouse connected as I was curious to see your Figma integration. Also looked at the code a bit (even though I have not written a Figma plugin yet). 

From my understanding your plugin is listening to scroll events and mapping them to the viewport when in Figma's design view ...is this correct?

I am thinking about a variation events where trigger transitions between frames in Figma's Prototype mode.

What events are communicated from the Spacemouse? And do you think this is in the realm of feasible within a Figma plugin?

Much appreciated,
Scott

**Comment by chuanqisun** [comment]
Hey Scott, the plugin is currently using the [HTML Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) to detect the movement of the knob. I have access to knob position in X, Y, Z and it [Roll, Pitch, Yaw](https://en.wikipedia.org/wiki/Aircraft_principal_axes). Scroll events are not used in this case. (I was listening to it to prevent unwanted scroll)

I'm not sure the Figma API allows you to make changes in Prototype mode ([this post](https://www.figma.com/plugin-docs/blog/2020/01/08/version-1-update-10/) says its "readonly"). It might be something possible in the future.
