### ISSUE TITLE
Plugin is disabled when driver modal is closed

### ISSUE THREAD

**Issue by mickdee** [chuanqisun/figma-plugin-spacemouse#3]
Awesome tool! The plugin works marvelously until I close the SpaceMouse Driver window, then it stops working. Is there a way to keep the plugin running in the background without having the driver window taking up space?

**Comment by coreyward** [comment]
@mickdee Plugins aren't able to run in the background today, but they may someday be supported. Relevant documentation is here: https://www.figma.com/plugin-docs/whats-supported/#long-running-background-plugins

**Comment by chuanqisun** [comment]
@coreyward is correct. It's a limit that all plugs are facing. I'd like to implement the background mode as soon as figma opens up the API. But before that happens, I plan to reduce the footprint of the interface to make it less intrusive. see #5
