### ISSUE TITLE
Support inverting zoom

### ISSUE THREAD

**Issue by coreyward** [chuanqisun/figma-plugin-spacemouse#4]
I tend to think of the Spacemouse handle as a handle on the model (or in this case, canvas). Thus pushing to the left moves the canvas to the left (effectively the same as scrolling right), and pulling the Spacemouse handle up moves the canvas closer (i.e. zooming _in_). 

This is not possible currently, but should be relatively straightforward to implement as an “Invert zoom” setting (following the established paradigm). I may take this on if I find myself with some time, but that's not likely for a while. 

Thanks for making this plugin regardless!

**Comment by chuanqisun** [comment]
I agree. Spacemouse uses a direct manipulation model in all its 3D applications. And to many users one way will be more "natural" than the other.  I should be able to get this in fairly easily.

Thanks for the suggestion!

**Comment by chuanqisun** [comment]
Implemented in a9aecab9da98139b6edc1fc942fb13bfd04ca981. Also added a 3D mode treats the canvas and the knob in the same spatial coordinate system.
![image](https://user-images.githubusercontent.com/1895289/82136096-cd2bc680-97be-11ea-920f-7de505c7858c.png)
