### ISSUE TITLE
Invert the XYZ axes

### ISSUE THREAD

**Issue by Evgenw** [chuanqisun/figma-plugin-spacemouse#7]
Hello friend, thanks a lot for the plugin!
For some reason I cannot invert the XYZ axes in the joystick driver, I like the 3D mode, but the direction of the axes is not convenient for me :(
how can they be changed? Thank you so much!

**Comment by chuanqisun** [comment]
Thank you @Evgenw. I'm sorry I've missed your issue. Can you provide a bit more detail on what's not working for you?

1. Does switching between Camera/2D/3D mode have any effect on your device?
2. What would work the best for you?
    1. When you push the knob forward/backward, what do you expect it to do?
    2. When you lift the knob up/push the knob down, what do you expect it to do?
    3. When you push the knob to left/right, what do you expect it do to?
    4. Do you expect the knob to do anything when you tilt it?

**Comment by Evgenw** [comment]
Hey! I'm glad you answered :)
1 forward / backward - zoom + / - (forward - zoom +, backward - zoom -)
2 up / press - page up / page down (similar to keys on a keyboard)
3 **Left** / _Right_ - **Page Right** / _Page Left_
4 No, I do not expect.

P.S. Too much sensitivity and the page in Figma shakes when I am not using the device, could you increase the starting force

Thank you so much!

**Comment by chuanqisun** [comment]
Thanks for the details! I can adjust the sensitivity or expose a configuration to let you adjust it.

Just want to double check your need to control the axes. Suppose this is your figma window:

![image](https://user-images.githubusercontent.com/1895289/111686407-42ed2e00-87e6-11eb-87a1-b471a5698758.png)

Is this how you want your device to work:
Push knob forward: see fewer squares
Lift knob up: center on square "2A"
Push knob left: center on square "3" <-- Did I get this right? Or you actually wanted to center on square "1"?

**Comment by Evgenw** [comment]
**Or you actually wanted to center on square "1"**
For me it is control like "Counter Strike" or other games. I hope you love video games too :)

Look

![123](https://user-images.githubusercontent.com/74410643/111751029-a76ac480-889c-11eb-9a81-8c3b2034d35b.jpg)

**Comment by chuanqisun** [comment]
Got it. So you want map the knob movement to the camera, instead of to the physical world. Most PC gamers prefer that.

I'll make that possible in Figma.

Thank you for the dust 2 illustration.

**Comment by chuanqisun** [comment]
@Evgenw , the latest version has addressed this issue. Just select `3D` and `Camera` in the options. 
![image](https://user-images.githubusercontent.com/1895289/111882391-883e6680-8972-11eb-84a0-00ab193f12db.png)

In addition, I added a subtle threshold for activation. This should help reduce the shaking.

Give it a try?

**Comment by Evgenw** [comment]
Thank you! Thank you so much!!!!
